### ISSUE TITLE
v0.9 release checklist

### ISSUE THREAD

**Issue by acobster** [sitecrafting/conifer#125]
- [ ] ~Refactor & test advanced search API #77~
- [x] Create a `release/v0.9.0 branch` (`release/v0.8.0` is now defunct)
- [x] Fix form bugs #128 #129
- [x] Drop VVV support
- [x] Update `get_context_with_post` reference https://coniferplug.in/#more-helpers
- [x] Dismissable Alert #120 
- [x] Lando rc.2+ dev environment
- [x] `Site::disable_comments()` convenience method
- [x] `_wp_page_template` shortcut admin column
